# Generated by Django 5.2.5 on 2025-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0025_highlight_highlightcomment_highlightshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightview',
            name='view_duration',
            field=models.FloatField(default=0.0, help_text='View duration in seconds'),
        ),
    ]
