# Generated by Django 5.2.5 on 2025-08-24 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blizzgame', '0026_add_view_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appreciation_count',
            field=models.IntegerField(default=0, help_text="Nombre total d'appréciations reçues"),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, help_text='Score basé sur les appréciations reçues'),
        ),
        migrations.CreateModel(
            name='HighlightAppreciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('appreciation_level', models.IntegerField(choices=[(1, 'Extrêmement nul'), (2, 'Pas terrible'), (3, 'Moyen'), (4, 'Bien'), (5, 'Très bien'), (6, 'Extraordinaire')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='blizzgame.highlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_appreciations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('highlight', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='HighlightLike',
        ),
    ]
